/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_bhdo;

import java.awt.Font;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PREDATOR
 */
public class Interface extends javax.swing.JFrame {
    private int Finales=12;
    private boolean punto=true;
    String valor1,valor2,signo,contenido;
    double resultado;
    int banderadecimal;
    String convercionoptions;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        Mostradortxt.setBackground(java.awt.Color.darkGray);
        Mostradortxt.setEditable(false);
        setLocationRelativeTo(null);
        setSize(950,600);
        setResizable(false);
        Font fuente=new Font("The Display St",6,45);
        Entradas.setFont(fuente);
        Mostradortxt.setFont(fuente);
        setTitle("CALCULADORA");
        setIconImage(new ImageIcon(getClass().getResource("/calculadora_bhdo/logo.png")).getImage());
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entradas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Divi_bt = new javax.swing.JButton();
        Multi_bt = new javax.swing.JButton();
        Resta_bt = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        Suma_bt = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_1 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_igual = new javax.swing.JButton();
        Reset_bt = new javax.swing.JButton();
        btn_cero = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mostradortxt = new javax.swing.JTextPane();
        hexadecimalbtn = new javax.swing.JButton();
        octalbtn = new javax.swing.JButton();
        binariobtn = new javax.swing.JButton();
        decimalbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(1000, 594));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(59, 58, 58));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));

        Entradas.setBackground(new java.awt.Color(33, 33, 33));
        Entradas.setForeground(new java.awt.Color(251, 251, 251));
        Entradas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradasActionPerformed(evt);
            }
        });
        Entradas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradasKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 251, 251));
        jLabel1.setText("Operaciones:");

        Divi_bt.setBackground(new java.awt.Color(39, 46, 46));
        Divi_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Divi_bt.setForeground(new java.awt.Color(251, 251, 251));
        Divi_bt.setText("/");
        Divi_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Divi_btActionPerformed(evt);
            }
        });

        Multi_bt.setBackground(new java.awt.Color(39, 46, 46));
        Multi_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Multi_bt.setForeground(new java.awt.Color(251, 251, 251));
        Multi_bt.setText("*");
        Multi_bt.setMaximumSize(new java.awt.Dimension(37, 25));
        Multi_bt.setMinimumSize(new java.awt.Dimension(37, 25));
        Multi_bt.setPreferredSize(new java.awt.Dimension(37, 25));
        Multi_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multi_btActionPerformed(evt);
            }
        });

        Resta_bt.setBackground(new java.awt.Color(39, 46, 46));
        Resta_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Resta_bt.setForeground(new java.awt.Color(251, 251, 251));
        Resta_bt.setText("-");
        Resta_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resta_btActionPerformed(evt);
            }
        });

        bt_9.setBackground(new java.awt.Color(39, 46, 46));
        bt_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_9.setForeground(new java.awt.Color(251, 251, 251));
        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        Suma_bt.setBackground(new java.awt.Color(39, 46, 46));
        Suma_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Suma_bt.setForeground(new java.awt.Color(251, 251, 251));
        Suma_bt.setText("+");
        Suma_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suma_btActionPerformed(evt);
            }
        });

        bt_7.setBackground(new java.awt.Color(39, 46, 46));
        bt_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_7.setForeground(new java.awt.Color(251, 251, 251));
        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_4.setBackground(new java.awt.Color(39, 46, 46));
        bt_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_4.setForeground(new java.awt.Color(251, 251, 251));
        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_6.setBackground(new java.awt.Color(39, 46, 46));
        bt_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_6.setForeground(new java.awt.Color(251, 251, 251));
        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_5.setBackground(new java.awt.Color(39, 46, 46));
        bt_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_5.setForeground(new java.awt.Color(251, 251, 251));
        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_1.setBackground(new java.awt.Color(39, 46, 46));
        bt_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_1.setForeground(new java.awt.Color(251, 251, 251));
        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_2.setBackground(new java.awt.Color(39, 46, 46));
        bt_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_2.setForeground(new java.awt.Color(251, 251, 251));
        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_3.setBackground(new java.awt.Color(39, 46, 46));
        bt_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_3.setForeground(new java.awt.Color(251, 251, 251));
        bt_3.setText("3");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_8.setBackground(new java.awt.Color(39, 46, 46));
        bt_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_8.setForeground(new java.awt.Color(251, 251, 251));
        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_igual.setBackground(new java.awt.Color(29, 181, 69));
        bt_igual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_igual.setForeground(new java.awt.Color(250, 247, 247));
        bt_igual.setText("=");
        bt_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_igualActionPerformed(evt);
            }
        });

        Reset_bt.setBackground(new java.awt.Color(213, 0, 0));
        Reset_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset_bt.setForeground(new java.awt.Color(246, 245, 245));
        Reset_bt.setText("CE");
        Reset_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btActionPerformed(evt);
            }
        });

        btn_cero.setBackground(new java.awt.Color(39, 46, 46));
        btn_cero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cero.setForeground(new java.awt.Color(251, 251, 251));
        btn_cero.setText("0");
        btn_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Suma_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Resta_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Multi_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Divi_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Divi_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multi_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resta_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suma_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Reset_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton14.setBackground(new java.awt.Color(228, 31, 31));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(253, 253, 253));
        jButton14.setText("SALIR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        Mostradortxt.setEditable(false);
        Mostradortxt.setForeground(new java.awt.Color(33, 33, 33));
        Mostradortxt.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane1.setViewportView(Mostradortxt);

        hexadecimalbtn.setBackground(new java.awt.Color(39, 46, 46));
        hexadecimalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hexadecimalbtn.setForeground(new java.awt.Color(251, 251, 251));
        hexadecimalbtn.setText("HEXADECIMAL");
        hexadecimalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexadecimalbtnActionPerformed(evt);
            }
        });

        octalbtn.setBackground(new java.awt.Color(39, 46, 46));
        octalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        octalbtn.setForeground(new java.awt.Color(251, 251, 251));
        octalbtn.setText("OCTAL");
        octalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalbtnActionPerformed(evt);
            }
        });

        binariobtn.setBackground(new java.awt.Color(39, 46, 46));
        binariobtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        binariobtn.setForeground(new java.awt.Color(251, 251, 251));
        binariobtn.setText("BINARIO");
        binariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binariobtnActionPerformed(evt);
            }
        });

        decimalbtn.setBackground(new java.awt.Color(39, 46, 46));
        decimalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        decimalbtn.setForeground(new java.awt.Color(251, 251, 251));
        decimalbtn.setText("DECIMAL");
        decimalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Entradas)
                            .addComponent(jScrollPane1)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(binariobtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(octalbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hexadecimalbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(decimalbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(127, 127, 127)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decimalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hexadecimalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(octalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(binariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String operaciones(String valor1,String valor2,String signo){
        Double resultadocal=0.0;
        String respuesta;
        if(signo.equals("+")){
        resultadocal=Double.parseDouble(valor1)+Double.parseDouble(valor2);
        }
        else if(signo.equals("-")){
        resultadocal=Double.parseDouble(valor1)-Double.parseDouble(valor2);
        }
        else if(signo.equals("*")){
         resultadocal=Double.parseDouble(valor1)*Double.parseDouble(valor2);
         }
         else if(signo.equals("/")){
         resultadocal=Double.parseDouble(valor1)/Double.parseDouble(valor2);
         }
        respuesta=resultadocal.toString();
    return respuesta;
    }
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void EntradasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradasKeyTyped
          char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') || (caracter > '9')) &&(caracter != '\b') && (caracter != '.') && (caracter != '-')){evt.consume();}
        if (caracter == '-' && Entradas.getText().contains("-")) {evt.consume();}
        if (caracter == '.' && Entradas.getText().contains(".")) {evt.consume();}
        if(Entradas.getText().length()>Finales){evt.consume();}

    }//GEN-LAST:event_EntradasKeyTyped

    private void bt_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_igualActionPerformed
        String resultadoFinal;
        valor2=Entradas.getText();
        if(!valor2.equals("")){
        resultadoFinal=operaciones(valor1,valor2,signo);
        Mostradortxt.setText(resultadoFinal);
        Entradas.setText(resultadoFinal);
        }
   
    }//GEN-LAST:event_bt_igualActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        Entradas.setText(Entradas.getText()+"7");
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        Entradas.setText(Entradas.getText()+"8");
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        Entradas.setText(Entradas.getText()+"9");
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        Entradas.setText(Entradas.getText()+"4");
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        Entradas.setText(Entradas.getText()+"5");
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        Entradas.setText(Entradas.getText()+"6");
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        Entradas.setText(Entradas.getText()+"1");
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        Entradas.setText(Entradas.getText()+"2");
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        Entradas.setText(Entradas.getText()+"3");
    }//GEN-LAST:event_bt_3ActionPerformed

    private void Reset_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btActionPerformed
        Entradas.setText("");
        Mostradortxt.setText("");
    }//GEN-LAST:event_Reset_btActionPerformed

    private void Suma_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suma_btActionPerformed
        if(!Entradas.getText().equals("")){
        valor1=Entradas.getText();
        signo="+";
        Entradas.setText("");
        }
    }//GEN-LAST:event_Suma_btActionPerformed

    private void Resta_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resta_btActionPerformed
        if(!Entradas.getText().equals("")){
        valor1=Entradas.getText();
        signo="-";
        Entradas.setText("");
        }
    }//GEN-LAST:event_Resta_btActionPerformed

    private void Multi_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multi_btActionPerformed
       if(!Entradas.getText().equals("")){
        valor1=Entradas.getText();
        signo="*";
        Entradas.setText("");
        }
    }//GEN-LAST:event_Multi_btActionPerformed

    private void Divi_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Divi_btActionPerformed
        if(!Entradas.getText().equals("")){
        valor1=Entradas.getText();
        signo="/";
        Entradas.setText("");
        }
    }//GEN-LAST:event_Divi_btActionPerformed

    private void decimalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalbtnActionPerformed
             if(!Entradas.getText().equals("")){
            double i=Double.parseDouble(Entradas.getText()); 
            String cap=Double.toString(i);
            Mostradortxt.setText(cap);
            }
            else{
             JOptionPane.showMessageDialog(null , "Verificar campo");
            }
    }//GEN-LAST:event_decimalbtnActionPerformed

    private void binariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binariobtnActionPerformed
            if(!Entradas.getText().equals("")){
        double i=Double.parseDouble(Entradas.getText());
            int bb=(int) i;    
            String cap=Integer.toBinaryString(bb);
            Mostradortxt.setText(cap);
            }
            else{
             JOptionPane.showMessageDialog(null , "Verificar campo");
            }
        
    }//GEN-LAST:event_binariobtnActionPerformed

    private void hexadecimalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexadecimalbtnActionPerformed
          if(!Entradas.getText().equals("")){
        double i=Double.parseDouble(Entradas.getText());
            int bb=(int) i;    
            String cap=Integer.toHexString(bb);
            Mostradortxt.setText(cap);
            }
            else{
             JOptionPane.showMessageDialog(null , "Verificar campo");
            }
    }//GEN-LAST:event_hexadecimalbtnActionPerformed

    private void octalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalbtnActionPerformed
          if(!Entradas.getText().equals("")){
        double i=Double.parseDouble(Entradas.getText());
            int bb=(int) i;    
            String cap=Integer.toOctalString(bb);
            Mostradortxt.setText(cap);
            }
            else{
             JOptionPane.showMessageDialog(null , "Verificar campo");
            }
    }//GEN-LAST:event_octalbtnActionPerformed

    private void btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceroActionPerformed
        Entradas.setText(Entradas.getText()+"0");
    }//GEN-LAST:event_btn_ceroActionPerformed

    private void EntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Divi_bt;
    private javax.swing.JTextField Entradas;
    private javax.swing.JTextPane Mostradortxt;
    private javax.swing.JButton Multi_bt;
    private javax.swing.JButton Reset_bt;
    private javax.swing.JButton Resta_bt;
    private javax.swing.JButton Suma_bt;
    private javax.swing.JButton binariobtn;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_igual;
    private javax.swing.JButton btn_cero;
    private javax.swing.JButton decimalbtn;
    private javax.swing.JButton hexadecimalbtn;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton octalbtn;
    // End of variables declaration//GEN-END:variables
}
